dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
- '8'
env:
  global:
  - NODE_ENV=test
cache:
  directories:
  - node_modules
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm set progress=false
- npm install -q
before_script:
- npm prune
after_success:
- npm run coverage
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
